### ISSUE TITLE
Nested lists format incorrectly

### ISSUE THREAD

**Issue by temyers** [HPouyanmehr/mui-markdown#1]
**Describe the bug**
A picture shows the issue clearly:

![image](https://user-images.githubusercontent.com/3837946/151948141-17115b27-ac3d-45b3-ad04-66a14e3b95d5.png)

For nested lists, the parent bullet point is incorrectly aligned

**To Reproduce**
Sample repository here: https://github.com/temyers/mui-markdown-nested-list

**Expected behavior**
Alignment such as:

* Foo
  * Bar
  * Baz

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: PopOS
 - Browser chromium
 - Version 95.0.4638.69

**Smartphone (please complete the following information):** - not tested

**Additional context**

**Comment by HPouyanmehr** [comment]
Hi @temyers, thank you for reporting this issue.

I've solved it, and the nested lists should now render properly. You need to update "mui-markdown" to the latest version (v0.5.2).

**Comment by temyers** [comment]
Awesome, thanks for the quick response.

Can confirm working a treat.
