### ISSUE TITLE
Cannot resolve markdown-to-jsx

### ISSUE THREAD

**Issue by ZehuaZhang** [HPouyanmehr/mui-markdown#13]
`yarn add mui-markdown`
Cannot resolve `markdown-to-jsx`

**Comment by HPouyanmehr** [comment]
Hey @ZehuaZhang,
I only publish the package to NPM, and the yarn one is added automatically. The `mui-markdown` uses the `markdown-to-jsx` and yarn tries to resolve and install dependencies differently from NPM. However, you can run `yarn add markdown-to-jsx` and then restart your project to solve this issue. 

I don't think that this is a `mui-markdown` issue.

**Comment by ZehuaZhang** [comment]
I did use `yarn add markdown-to-jsx`, but it seems not working either, my yarn version is `3.5.1`

**Comment by HPouyanmehr** [comment]
Can you provide a link to your Repo, or create a reproduction Repo if yours is private. Currently, it's hard to find the issue and solve it.

I added an example for yarn installation, and it is working properly. ([Check it here](https://github.com/HPouyanmehr/mui-markdown/tree/main/examples/yarn-installation))

**Comment by HPouyanmehr** [comment]
I close this as it is not a valid `mui-markdown` issue.

**Comment by ZehuaZhang** [comment]
The installation is correct, but when using with react, it complains
