### ISSUE TITLE
Syntax Highlight properties are not applied when used in combination with overrides

### ISSUE THREAD

**Issue by grajdeanserghei** [HPouyanmehr/mui-markdown#17]
**Describe the bug**
Syntax Highlight properties (`Highlight`, `themes`, `prismTheme`) are ignored when combined with `overrides` .

This code won't highlight the source code:
```js
<MuiMarkdown
        Highlight={Highlight}
        themes={themes}
        prismTheme={themes.github}
        overrides={{
          ...getOverrides({}), // This will keep the other default overrides.
          h1: {
            component: "p",
            props: {
              style: { color: "red" },
            },
          },
        }}
      >
        {`\`\`\`java
          class HelloWorld {
        }
        \`\`\`
        `}
      </MuiMarkdown>
```

When combined with `overrides` it needs to be written as:

```js
<MuiMarkdown
        overrides={{
          ...getOverrides({ Highlight, themes, theme: themes.duotoneDark }), // This will keep the other default overrides.
          h1: {
            component: "p",
            props: {
              style: { color: "red" },
            },
          },
        }}
      >
         {`\`\`\`java
          class HelloWorld {
        }
        \`\`\``}
      </MuiMarkdown>
```
Probably interface of `MuiMarkdown` component can be changed to have just one way of providing Syntax Highlight properties. 

If this is the intended behavior, I suggest at least updating documentation to reflect this behavior.

**To Reproduce**
1. Install `prism-react-renderer` 
2. Create the component
```js
<MuiMarkdown
        Highlight={Highlight}
        themes={themes}
        prismTheme={themes.github}
        overrides={{
          ...getOverrides({}), // This will keep the other default overrides.
          h1: {
            component: "p",
            props: {
              style: { color: "red" },
            },
          },
        }}
      >
        {`\`\`\`java
          class HelloWorld {
        }
        \`\`\`
        `}
      </MuiMarkdown>
```

**Expected behavior**
Code highlighting styles are applied.

**Additional context**
I can submit a PR to update the documentation

**Comment by HPouyanmehr** [comment]
Hey @grajdeanserghei, thanks for the explanation
>  If this is the intended behavior, I suggest at least updating documentation to reflect this behavior.

Yes, this is the correct behavior, and it is mentioned in the documentation as well at the end of [Props section](https://github.com/HPouyanmehr/mui-markdown/tree/main#props) 

> Note: You cannot use overrides and options at the same time.

By the way if you think there is a better way to reflect this behavior you're welcome for the PR.

**Comment by grajdeanserghei** [comment]
Hi @HPouyanmehr, thanks for the replay.
Sorry, I did not notice the `Note` part. 
I'll think how to make it more visible and submit a PR.

Thanks for your hard work on this library.

**Comment by HPouyanmehr** [comment]
You're welcome. Thanks for the participation.

As the reported issue isn't a bug, I'm going to close this issue.By the way, You can link the PR to this issue as an enhancement.
