### ISSUE TITLE
MuiMarkdown hangs the system indefinitely when the string is of a particular shape

### ISSUE THREAD

**Issue by narcis-fv** [HPouyanmehr/mui-markdown#23]
**Describe the bug**
The parsing hangs indefinitely when the string contains is a new line, a lot of spaces, and then a new line again.
Example string:  "t\n                                                                                                 \nt";

Note: The spaces between the new lines are being removed by the github parser (gj github), so I'll attach a screenshot:
![image](https://github.com/user-attachments/assets/bf3d9268-18d4-46f6-93eb-26969941bb23)

**To Reproduce**
Try to run the string above through MuiMarkdown

**Additional context**
Downgrading markdown-to-jsx to 7.1.5 fixes the issue.

**Comment by HPouyanmehr** [comment]
Hey @narcis-fv, thanks for reporting this

First of all, If you write the content directly in a `.md` or `.mdx` file, you can use `↵ Enter` or `<br/>` for the new lines as `\n`  is not interpreted as a line break in markdown. 
I replaced `\n` with `<br />` in your example and it worked correctly without hanging. Or if you fetch the content from somewhere else you can try to replace all `\n` with `<br />` in JS as a workaround.

By the way, As I tested, I believe this isn't a `mui-markdown` issue and so please report it on the [`markdown-to-jsx`](https://github.com/quantizor/markdown-to-jsx/issues) if the issue remains.

**Comment by narcis-fv** [comment]
Hi @HPouyanmehr , thanks for replying. 

Unfortunately I have to disable parsing raw html, so this fix wouldn't work. Going to contact markdown-to-jsx as well.
