### ISSUE TITLE
Dependency conflict with MUI v6

### ISSUE THREAD

**Issue by mauro-ni** [HPouyanmehr/mui-markdown#27]
**Describe the bug**
There is a dependency conflict when already on MUI v6

**To Reproduce**
1. Update an existing application to MUI 6
2. Execute yarn install
3. See error (screenshot below)

**Expected behavior**
Support for MUI v6

**Screenshots**
![Screenshot 2024-08-29 at 17 06 55](https://github.com/user-attachments/assets/7a91d0cb-1d9d-4527-865a-e7fac43431b5)

**Comment by HPouyanmehr** [comment]
Hey @mauro-ni, Thanks for reporting this.

I've fixed the "peerDeps" issue and you can update to [v1.2.2](https://github.com/HPouyanmehr/mui-markdown/releases/tag/v1.2.2).

**Comment by mauro-ni** [comment]
@HPouyanmehr many thanks!!!
