### ISSUE TITLE
Problem when rendering code block with list item

### ISSUE THREAD

**Issue by bqhuyy** [HPouyanmehr/mui-markdown#28]
**Describe the bug**
Code block cannot render correctly

**To Reproduce**
- Try to render this `msg`
```jsx
const msg = `
* Here is an example:
\`\`\`python
import os

a = 1
b = 10
\`\`\`
`

<MuiMarkdown Highlight={Highlight}
  themes={themes}
  prismTheme={themes.github}
  hideLineNumbers
  options={{ disableParsingRawHTML: true }}>
  {msg}
</MuiMarkdown>
```

**Expected behavior**
Code block can render

**Screenshots**
![Screenshot 2024-09-04 165829](https://github.com/user-attachments/assets/dd142961-be82-44a6-a0d2-217e686c90f2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 128.0.6613.119

**Additional context**

**Comment by HPouyanmehr** [comment]
Hey @bqhuyy, Sorry for the delay.

The issue you're facing is a core issue in `markdown-to-jsx` and it's out of the scope of this package. However, adding a new line after the list can help you achieve what you need.

![Issue Workaround](https://github.com/user-attachments/assets/847722fe-062b-4578-931f-1c208ecef7aa)
