### ISSUE TITLE
Documentation isn't clear on how to integrate it with mdx

### ISSUE THREAD

**Issue by ItsBenDov** [HPouyanmehr/mui-markdown#29]
**Is your feature request related to a problem? Please describe.**
After looking at the documentation, and looking for answers online, I cant understand how should I use this with NextJS and the `useMDXcomponents `function. Specifically, the documentation suggests that the `<MuiMarkdown>` tag should wrap strings, but it is not clear how this applies when rendering MDX components like <Explanation />.

**Describe the solution you'd like**
Improve the documentation for mdx components.

**Additional context**
This is my first time ever submitting a Github issue, so sorry if this problem is not well articulated or if I’ve missed providing some details. I'm happy to clarify further if needed.

**This is my code:**

page.tsx:
```tsx
import React from "react";
import { getOverrides, MuiMarkdown } from "mui-markdown";
import Explanation from "@/markdown/about.mdx";

const App = async () => {
//the Explanation component isn't styled with the Mui theme.
  return <Explanation />;
};

export default App;
```

mdx-components.tsx:
```tsx
import type { MDXComponents } from 'mdx/types';
import { MuiMarkdown } from 'mui-markdown';

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    ...components,
    
  };
}
```

**Comment by HPouyanmehr** [comment]
Hi @ItsBenDov, Thanks for reporting this, you did explain it well!

I've updated the package and added related utilities. Update to [v1.2.4](https://github.com/HPouyanmehr/mui-markdown/releases/tag/v1.2.4).

The package now exports two new things, `defaultMdxComponents` and `getMdxComponents`. You can import and add it to the `useMDXComponents` like this:

```tsx
import type { MDXComponents } from 'mdx/types';

import { defaultMdxComponents, getMdxComponents } from 'mui-markdown';

// You can use the getMdxComponents(options) to override defaults!
// const mdxComponents = getMdxComponents();

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    // ...mdxComponents,
    ...defaultMdxComponents,
    ...components,
  };
}
```

I did add [the relevant section](https://github.com/HPouyanmehr/mui-markdown?tab=readme-ov-file#use-with-usemdxcomponents) to the documentation as well. 

Also, feel free to comment or open this again if the issue remains!

**Comment by ItsBenDov** [comment]
Thank you so much!
Just a small question, how can I add custom styles to element tags, such as `h1`, `h2`, etc.. ?
The `options` and the `overrides` elements aren't available on `getMdxComponents`, and I couldn't figure this out from the documentation :(

**Comment by HPouyanmehr** [comment]
You're welcome!

If you want to change a component style, let's say the 'h1' component, you can extend the `defaultMDXComponents` in this way:

```ts
...
// Extend the defaults
const customComponents: MDXComponents = {
    ...defaultMdxComponents,
  h1: ...
};

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    ...customComponents,
    ...components,
  };
}
...
```
Edit: Use a custom h1 component 

Thanks. It is a nice idea to have the `options` and `overrides` available here! I hope to find free time soon to add them. Also, contributions are welcomed in `mui-markdown`!

**Comment by ItsBenDov** [comment]
Thank you @HPouyanmehr for the explanation!  I did find a way to do this, it would be a nice feature to have 😄, but no worries take your time

**Comment by HPouyanmehr** [comment]
Hey @ItsBenDov, from [v2.0.0](https://github.com/HPouyanmehr/mui-markdown/releases/tag/v2.0.0) you can also add properties and overrides to the `getMdxComponents` function.
