### ISSUE TITLE
rehype / remark example?

### ISSUE THREAD

**Issue by skyl** [HPouyanmehr/mui-markdown#3]
Great project!

Is it possible to pass remark and rehype plugins in? Thanks!

**Comment by HPouyanmehr** [comment]
Hi, 
Thanks, I'm glad that you liked it.

The short answer to your question: NO, it's not possible.

Currently, I'm working on another project, and I don't have enough time to improve and add more features to "mui-markdown". But I hope to find some time soon for that and also add features like what you asked about. Furthermore, everyone is welcome to add features and improve "mui-markdown" and I'll appreciate it.

**Comment by skyl** [comment]
thanks @hajhosein! I went with a homegrown lower-level solution but I learned a lot from your effort here.
