### ISSUE TITLE
error is raised if text is null

### ISSUE THREAD

**Issue by ebengtso** [HPouyanmehr/mui-markdown#5]
**Describe the bug**
mii-markdown raises error if text is null

**To Reproduce**
var anullvar=null;
<MuiMarkdown>{anullvar}</MuiMarkdown>

**Expected behavior**
Silently ignore and render empty

**Smartphone (please complete the following information):**
Chrome, Safari

**Additional context**
Latest version

**Comment by HPouyanmehr** [comment]
Hi, thank you for the report.
I've fixed this issue and you can safely update the package and pass the `null` value to the `MuiMarkdown` component with no error.

However, it's worth mentioning that even though it is now possible you should avoid that. It's better to check your variable and if it is null or empty don't render the component at all as it will just create an extra node on the dom without any usage. Here is an example of a better approach:

```ts
...
const aVariable = null;

return (
    <>
        {aVariable && <MuiMarkdown>{aVariable}</MuiMarkdown>}
    </>
)

...
```
