### ISSUE TITLE
Make Prism an optional dependency

### ISSUE THREAD

**Issue by Dianliang233** [HPouyanmehr/mui-markdown#6]
**Is your feature request related to a problem? Please describe.**
In some use cases, syntax highlighting isn't necessary. However, Prism ships an extra ~100KiB of JavaScript.

**Describe the solution you'd like**
Make Prism an optional dependency or find a way to tree-shake it.

By the way, very nice and straightforward library ❤️

**Comment by HPouyanmehr** [comment]
Hi, I'm glad that you've liked it.

Thanks for the enhancement suggestion. You're right. It's better to have Prism when it is needed. I'll work on that in my free time as it may require some time. Also, all contributions are welcomed.

**Comment by oezi** [comment]
@HPouyanmehr: did yu already start working on this? [prism-react-renderer](https://github.com/FormidableLabs/prism-react-renderer/releases/tag/prism-react-renderer%402.0.0) released a 2.0 yesterday, so if you still plan to make it an optional dependeny, it might be worth it to upgrade the version while at it.

**Comment by HPouyanmehr** [comment]
Hi @oezi, Thanks for the comment,

I think I can find some free time on this weekend to make `prism-react-renderer` optional and update the dependencies. I'll let you know as soon as I publish the updates.

**Comment by HPouyanmehr** [comment]
Hi @Dianliang233 and @oezi,

The `prism-react-renderer` is an optional dependency now from the [version 1.0.0](https://github.com/HPouyanmehr/mui-markdown/releases/tag/v1.0.0) and the dependencies has been updated.

Also sorry for the delay, I couldn't find enough time sooner.

Edit: Checkout [here](https://github.com/HPouyanmehr/mui-markdown#syntax-highlight) to see how to use syntax highlighter.

**Comment by oezi** [comment]
Hey @HPouyanmehr, thanks a lot for the fast update, dont worry about breaking your (entirely self-imposed 😉) deadline, and keep up the great work 👍

**Comment by HPouyanmehr** [comment]
@oezi 
You're welcome.
