### ISSUE TITLE
Is it possible to hotlink images?

### ISSUE THREAD

**Issue by xeniyandkn** [HPouyanmehr/mui-markdown#7]
Other markup libraries I have seen could hotlink images with the following format `![]()`
It would be great to have it here.

**Comment by HPouyanmehr** [comment]
Hi,
The syntax that you want is supported in the current version and will render the image correctly.

Here is an example:
```tsx
...
<MuiMarkdown>
    {'![Some Random Image](https://picsum.photos/100/100)'}
</MuiMarkdown>
...
```
---
However if you want to have something equivalent to the following code in your MD the syntax is different:
```html
<a href="https://picsum.photos">
    <img alt="Some Random Image" src="https://picsum.photos/100/100">
</a>
```
for the MD it'll be:
```tsx
...
<MuiMarkdown>
    {'[![Some Random Image](https://picsum.photos/100/100)](https://picsum.photos)'}
</MuiMarkdown>
...
```

Both cases are supported in the current version.
* `![]()`
*  `[![]()]()`

**Comment by xeniyandkn** [comment]
> Hi, The syntax that you want is supported in the current version and will render the image correctly.
> 
> Here is an example:
> 
> ```tsx
> ...
> <MuiMarkdown>
>     {'![Some Random Image](https://picsum.photos/100/100)'}
> </MuiMarkdown>
> ...
> ```
> 
> However if you want to have something equivalent to the following code in your MD the syntax is different:
> 
> ```
> <a href="https://picsum.photos">
>     <img alt="Some Random Image" src="https://picsum.photos/100/100">
> </a>
> ```
> 
> for the MD it'll be:
> 
> ```tsx
> ...
> <MuiMarkdown>
>     {'[![Some Random Image](https://picsum.photos/100/100)](https://picsum.photos)'}
> </MuiMarkdown>
> ...
> ```
> 
> Both cases are supported in the current version.
> 
> * `![]()`
> * `[![]()]()`

this is amazing! you're absolutely right, thank you for a quick response!
