### ISSUE TITLE
Can't override MuiMarkdownProps, children prop

### ISSUE THREAD

**Issue by antokhio** [HPouyanmehr/mui-markdown#8]
**Describe the bug**
Hi, trying to override `MuiMarkdownProps` type to extend children to be `string | null | undefined`
I need it because default value for string in database is null...

I do: 
```ts
export type MarkdownProps = Omit<MuiMarkdownProps, 'children'> & {
  children: string | null | undefined;
};
```
I get: 
```
Types of property 'overrides' are incompatible.
      Type 'Overrides | undefined' is not assignable to type 'undefined'.
        Type 'Overrides' is not assignable to type 'undefined'.
```

So the issue seems to be the underlying type.

**Additional context**

The easy fix would be to add `null` to:
```ts
export interface MuiMarkdownRootProps {
    children?: string;
    prismTheme?: PrismTheme;
    codeWrapperStyles?: CSSProperties;
    Highlight?: HighlightComponent;
    themes?: HighlightThemes;
}
```

Thanks for the efforts!

**Comment by HPouyanmehr** [comment]
Hi @antokhio, Thanks for your suggestion.

You can check the children to see if it's a null value or not like this:
```ts
...
<MuiMarkdown>{children ? children : ''}</MuiMarkdown>
...
```

However, I have added the type to the default props to be able to pass the `null` value as well. You just need to update to [`v1.0.1`](https://github.com/HPouyanmehr/mui-markdown/releases/tag/v1.0.1).
